name: SpeedChallenge
main: io.github.itachi1706.SpeedChallenge.Main
version: 1.5
description: A plugin for a speed challenge game
author: itachi1706
depend: [Multiverse-Core]
commands:
  sc:
    description: Main Plugin Command
    usage: /sc reset
    permission: sc.debug
    permission-message: You do not have permission to do this command
  scconfig:
    description: Resets Game
    usage: /sc reset
    permission: sc.debug
    permission-message: You do not have permission to do this command
  spectate:
    description: Resets Game
    usage: /sc reset
    permission: sc.debug
    permission-message: You do not have permission to do this command
  listobjectives:
    description: List objectives
    usage: /listobjectives
    permission: sc.debug
    permission-message: You have perms no matter what :D
  reequip:
    description: Reequips with item
    usage: /reequip
    permission: sc.debug
    permission-message: You have perms no matter what :D
  scadmin:
    description: Force Starts Game
    usage: /scadmin forcestart/endgame
    permission: sc.override
    permission-message: You do not have permission to do this command
permissions:
  sc.debug:
    description: Debug
    default: true
  sc.override:
    description: Allows overriding of stuff
    default: op