name: JukeboxSequence
main: com.itachi1706.Bukkit.JukeboxSequence.Main
version: 1.9
description: An loop for jukeboxes
author: itachi1706
commands:
  js:
    description: Main Plugin Command
    usage: /js reload/stop/start/debug/status
    permission: jukeboxsequence.staff
    permission-message: You do not have permission to do this command
    aliases: [jukeboxsequence]
  nowplaying:
    description: See what is currently playing
    usage: /nowplaying
    permission: jukeboxsequence.default
    permission-message: You do not have permission to do this command
  fixsong:
    description: Skips songs to coordinate them
    usage: /fixsong
    permission: jukeboxsequence.staff
    permission-message: You do not have permission to do this command
    aliases: [skipsong]
permissions:
  jukeboxsequence.default:
    description: Default command
    default: true
  jukeboxsequence.staff:
    description: Staff command
    default: op