name: CheesecakeLogger
main: com.itachi1706.Bukkit.CheesecakeLogger.Main
version: 0.0.4
description: A logging plugin
author: itachi1706
depend: [SQLibrary]
commands:
  lastseen:
    description: Last seen Command
    usage: /lastseen <player>
    permission: cheesecakelogger.default
    permission-message: You do not have permission to do this command.
    aliases: [seen]
  cheesecakelogger:
    description: Main Command
    usage: /cheesecakelogger help
    permission: cheesecakelogger.default
    permission-message: You do not have permission to do this command.
  viewlogins:
    description: View login and logout history of a player
    usage: /viewlogins <player> <#>
    permission: cheesecakelogger.logs
    permission-message: You do not have permission to do this command.
  viewplayerstats:
    description: View login and logout history of a player
    usage: /viewplayerstats <player>
    permission: cheesecakelogger.logs
    permission-message: You do not have permission to do this command.
  delloginhistory:
    description: Delete login and logout history of a player
    usage: /delloginhistory <player>
    permission: cheesecakelogger.admin
    permission-message: You do not have permission to do this command.
permissions:
  cheesecakelogger.default:
    description: Default command
    default: true
  cheesecakelogger.logs:
    description: View logs
    default: op
  cheesecakelogger.admin:
    description: Admin command
    default: op
