name: NickNamer
main: com.itachi1706.Bukkit.NickNamer.Main
version: 1.4
description: A plugin to nick into other players
author: itachi1706
depend: [TagAPI]
commands:
  nick:
    description: Nicks player or other players nicknames
    usage: 
      /nick <nick> - Nicks yourself to another player.
      /nick <player> <nick> - Nicks another player to nickname
    permission: nicknamer.nick
    permission-message: You do not have permission to do this command.
  nickreset:
    description: Reset player or other players nicknames
    usage:
      /nickreset - Resets your nickname
      /nickreset <player> - Resets nick of another player
    permission: nicknamer.nick.reset
    permission-message: You do not have permission to do this command.
  nn:
    description: Reloads plugins and refreshes nicked players
    usage: /nn reload
    permission: nicknamer.nick.reload
  realname:
    description: See real name of nicked player
    usage: /realname <player>
    permission: nicknamer.nick.realname
  togglenick:
    description: Disguise as an ordinary member
    usage: /togglenick [player]
    permission: nicknamer.nick.disguise
permissions:
  nicknamer.*:
    description: Grants access to all Nicknamer commands
    children:
      nicknamer.nick.*: true
      nicknamer.color.*: true
      nicknamer.format.*: true
  nicknamer.nick.staff:
    description: Allows access to all staff commands
    children:
      nicknamer.nick.realname: true
      nicknamer.nick.reload: true
      nicknamer.nick.disguise: true
      nicknamer.nick.disguise.other: true
      nicknamer.nick.isstaff: true
  nicknamer.nick.*:
    description: Gives access to all nick commands
    children:
      nicknamer.nick: true
      nicknamer.nick.other: true
      nicknamer.nick.reset: true
      nicknamer.nick.reset.other: true
  nicknamer.nick.self:
    description: Allows you to nick and reset nick
    children:
      nicknamer.nick: true
      nicknamer.nick.reset: true
  nicknamer.nick.other:
    description: Allows you to nick and reset nick of others
    children:
      nicknamer.nick.other: true
      nicknamer.nick.reset.other: true
  nicknamer.color.*:
    description: Allows access to all colors (for OP negating)
    children:
      nicknamer.color.black: true
      nicknamer.color.dark_blue: true
      nicknamer.color.dark_green: true
      nicknamer.color.dark_aqua: true
      nicknamer.color.dark_red: true
      nicknamer.color.dark_purple: true
      nicknamer.color.gold: true
      nicknamer.color.gray: true
      nicknamer.color.dark_gray: true
      nicknamer.color.blue: true
      nicknamer.color.green: true
      nicknamer.color.aqua: true
      nicknamer.color.red: true
      nicknamer.color.light_purple: true
      nicknamer.color.yellow: true
      nicknamer.color.white: true
  nicknamer.format.*:
    description: Allows access to all formats (for OP negating)
    children:
      nicknamer.format.magic: true
      nicknamer.format.bold: true
      nicknamer.format.strikethrough: true
      nicknamer.format.underline: true
      nicknamer.format.italic: true
  nicknamer.nick:
    description: Allows you to get a nickname
    default: op
  nicknamer.nick.other:
    description: Allows you to nick others
    default: op
  nicknamer.nick.reset:
    description: Allows you to reset nick
    default: op
  nicknamer.nick.reset.other:
    description: Allows you to reset other's nick
    default: op
  nicknamer.nick.realname:
    description: Allows you to find out the real name of the player in nick.
    default: op
  nicknamer.nick.reload:
    description: Reloads the plugin and refreshes nicked players
    default: op
  nicknamer.nick.disguise:
    description: Allows access to the /togglenick command
    default: op
  nicknamer.nick.disguise.other:
    description: Allows access to /togglenick for others
    default: op
  nicknamer.color.black:
    description: Black color
    default: false
  nicknamer.color.dark_blue:
    description: Dark Blue color
    default: false
  nicknamer.color.dark_green:
    description: Dark Green color
    default: false
  nicknamer.color.dark_aqua:
    description: Dark Aqua color
    default: false
  nicknamer.color.dark_red:
    description: Dark Red color
    default: false
  nicknamer.color.dark_purple:
    description: Dark Purple color
    default: false
  nicknamer.color.gold:
    description: Gold color
    default: false
  nicknamer.color.gray:
    description: Gray color
    default: false
  nicknamer.color.dark_gray:
    description: Dark Gray color
    default: false
  nicknamer.color.blue:
    description: Blue color
    default: false
  nicknamer.color.green:
    description: Green color
    default: false
  nicknamer.color.aqua:
    description: Aqua color
    default: false
  nicknamer.color.red:
    description: Red color
    default: false
  nicknamer.color.light_purple:
    description: Light Purple color
    default: false
  nicknamer.color.yellow:
    description: Yellow color
    default: false
  nicknamer.color.white:
    description: White color
    default: false
  nicknamer.format.magic:
    description: Magic format
    default: false
  nicknamer.format.bold:
    description: Bold format
    default: false
  nicknamer.format.strikethrough:
    description: Strikethrough format
    default: false
  nicknamer.format.underline:
    description: Underline format
    default: false
  nicknamer.format.italic:
    description: Italic format
    default: false
  nicknamer.nick.isstaff:
    description: Staff Member
    default: op
  nicknamer.nick.isyt:
    description: YouTuber
    default: false