name: MemberSigns
main: com.itachi1706.Bukkit.MemberSigns.Main
version: 1.2
description: An internal plugin for Member signs and colors :D
author: itachi1706
permissions:
  membersigns.admin:
    description: Allows you to use MemberSigns
    default: op