#File config version number (Do not touch)
version: 1

#Mode in which the plugin will act in (lobby, adv, survival)
mode: lobby

#lobby mode
#%prefix% - displays User Prefix
#%playername% - Display player name
lobbymsg:
  - '&6====================================================='
  - '&2Welcome %prefix% %playername% &2to the &6Cheesecake Network!'
  - '&2Use the compass to go to other servers!'
  - '&2The book in your inventory will have more information!'
  - '&2To hide players, use the Eye Of Ender!'
  - '&2Teleport to other areas of the map with the Clock!'
  - '&6====================================================='

hubworld: world

#Adventure mode
#%prefix% - displays User Prefix
#%playername% - Display player name
#%mapauthor% - Current Map Author
#%mapname% - Current Map Name
mapname: 'NIL'
mapauthor: 'NIL'
advmsg:
  - '&6====================================================='
  - '&2                        Adventure Server'
  - '&6====================================================='
  - '&2Welcome %prefix% %playername%&2 to &4%mapname%'
  - '&2This map is made by &1%mapauthor%'
  - '&2Please obey all map rules'
  - '&2To return to the main lobby, do &6/hub'
  - '&6====================================================='

modules:
  fly: true
  speed: true
  smite: true
  zeus: true
  fling: true
  burn: true
  wow: true

#Survival mode
#%prefix% - displays User Prefix
#%playername% - Display player name
#%time% - Current time of the server
#%world% - Current world of the player
#%online% - Number of Online Players
#%players% - List of players
survmsg:
  - '&6====================================================='
  - '&2                         Survival World'
  - '&6====================================================='
  - '&2Hello, %prefix% %playername%&2!'
  - '&2The time is &9%time%&2 and you are in the world &9%world%&2.'
  - '&2Number of players currently online: &a%online%'
  - '&2Players online: %players%'
  - '&2Make sure to obey all &4Server Rules&2.'
  - '&2They can be found by doing &6/rules'
  - '&2Do &6/hub&2 to return to the lobby!'
  - '&6====================================================='
playerlistformat: '%prefix% %playername%'