name: Monopoly
main: com.itachi1706.Bukkit.Monopoly.Monopoly
version: 1.1
description: A Monopoly plugin
author: itachi1706
depend: [SQLibrary]
commands:
  monopoly:
    description: Monopoly commands
    usage: 
      /monopoly - Main plugin command
      /monopoly start - Starts (Resume) the game (Config has start = 1, pause = 0)
      /monopoly pause - Pauses the game (Config file has value start = 1, pause = 1)
      /monopoly reset - Resets the game (Set start = 0 in config)
      /monopoly join - Joins the game
      /monopoly leave - Leaves the game
      /monopoly join/leave <player> - Adds or Kicks a player from the game
      /monopoly give <property/gold> <player> <value/amount> - Gives a player a property (based on pos number) or gold
      /monopoly take <property/gold> <player> <value/amount> - Takes a property (based on pos number) or gold from player
      /monopoly reload - Reloads the files (will cause game to reset automatically)
      /monopoly dice - See the current value of the dice (will get and save to config file)
      /monopoly where [player] - Finding out the current location on the gameboard for you/other players
      /monopoly chatcmd - Finds out what chat commands there are
      /monopoly region <id> - Defines a region (0-39)
    permission: monopoly.normal
    permission-message: You do not have permission to do this command.
permissions:
  monopoly.normal:
    description: Allows you to play monopoly
    default: true
  monopoly.admin:
    description: Allows you to be an admin
    default: op